---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
spec:
  type: {{ if .Values.nodePort.enabled }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
      {{- if .Values.nodePort.enabled }}
      nodePort: {{ .Values.nodePort.nodePort }}
      {{- end }}
  selector:
    app: prometheus
